package exception;

public class Use_of_trow1 {
	public static void main(String[] args) throws Throwable {
		
		System.out.println("throw is raise the exception");
		
		throw new Throwable();
		
		
		
		
	}

}
